name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Recreate google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK (release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
